### ISSUE TITLE
[meta] Tracking rustc bugs/features/RFCs that affect bindgen

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#849]
This is a meta issue tracking rustc bugs and features that impact bindgen.

Appropriate things to list here would be either
* RFCs proposing some feature that bindgen can leverage to emit better bindings, or
* issues detailing rustc bugs we need fixed as a prerequisite to fixing bugs in our emitted bindings, or
* pull requests adding new features that enable us to emit new kinds of bindings we haven't been able to before.

-------------------------------------------

* [ ] Extern types: https://github.com/rust-lang/rust/issues/43467

* [ ] `u128` / `i128` https://github.com/rust-lang/rust/issues/35118

* [ ] `#[repr(align="N")]` https://github.com/rust-lang/rust/issues/33626

* [ ] `#[repr(packed="N")]` https://github.com/rust-lang/rust/issues/33158

* [ ] Support for `thiscall` calling convention https://github.com/rust-lang/rust/issues/42202

* [ ] Support for the System V AMD64 C++ ABI https://github.com/rust-lang/rust/issues/36167

* [ ] Support for placement new https://github.com/rust-lang/rust/issues/27779

**Comment by CensoredUsername** [comment]
FYI: the system V AMD4 ABI will be stabilized in rustc 1.24

**Comment by fitzgen** [comment]
> FYI: the system V AMD4 ABI will be stabilized in rustc 1.24

Thanks for the heads up!

**Comment by fitzgen** [comment]
As @upsuper pointed out, it looks like `repr(align = "N")` is being stabilized: https://github.com/rust-lang/rust/pull/47006

I'm not sure what version it will hit stable in.

**Comment by pravic** [comment]
> I'm not sure what version it will hit stable in.

From the PR:

> (accepted, repr_align, ["1.24.0"](https://github.com/rust-lang/rust/pull/47006/files#diff-8fe611e80215042c8d89714f4dd6f8baR546), Some(33626)),

**Comment by Dr-Emann** [comment]
As of [Rust 1.28](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1280-2018-08-02), `#[repr(transparent)` is stable.
