### ISSUE TITLE
Meta: ease contributing to bindgen

### ISSUE THREAD

**Issue by fitzgen** [servo/rust-bindgen#92]
Ramping up on bindgen as a newcomer is harder than it should be (eg https://github.com/servo/rust-bindgen/issues/51#issuecomment-254314540) so we should make it easier. This will serve as a meta bug for such issues.

Will add more here as file more issues.

* [x] Make `cargo test` work: #51
* [x] Add a `CONTRIBUTING.md` file w/ an overview of bindgen's architecture: #93
* [x] Add `#![deny(missing_docs)]`: #94 
* [x] Don't run tests expected to fail if `--features llvm_stable` is missing: #97

**Comment by fitzgen** [comment]
I think we can close this now :)

Hopefully it is a lot easier to get started hacking on bindgen now :)
